spring:
  datasource:
    username: root
    password: root
#    password: root1234!@#$
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_delivery?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
  jackson:
    time-zone: GMT+8
logging:
  level:
    root: info

image:
  path: /data/images
  type: png,jpg,jpeg
  size: 2097152
  scaleRatio: 0.20f



server:
  port: 8888

mybatis:
  type-aliases-package: com.wangyao.company.delivery.dao.mapper
  configuration:
    cache-enabled: true